#   MONITOR CONFIGURATION
# ████████████████████████████████████████████████████████████████████████████████

# Встроенный дисплей ноутбука
monitor = eDP-1, preferred, auto, 1

# Внешние мониторы (автоматическое определение)
monitor = , preferred, auto, 1
